@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	add	r4, r0, #0
	ldr	r5, .L3
	ldrb	r2, [r4]
	mov	r6, #1
	and	r2, r2, r6
	ldrb	r3, [r5]
	mov	r1, #2
	neg	r1, r1
	and	r1, r1, r3
	orr	r1, r1, r2
	ldrb	r2, [r4, #1]
	and	r2, r2, r6
	lsl	r2, r2, #1
	mov	r3, #3
	neg	r3, r3
	mov	r8, r3
	and	r1, r1, r3
	orr	r1, r1, r2
	ldrb	r2, [r4, #2]
	mov	r3, #31
	and	r2, r2, r3
	lsl	r2, r2, #2
	mov	r3, #125
	neg	r3, r3
	and	r1, r1, r3
	orr	r1, r1, r2
	strb	r1, [r5]
	ldrb	r2, [r4, #3]
	mov	r1, #31
	and	r2, r2, r1
	lsl	r2, r2, #7
	ldrh	r3, [r5]
	ldr	r1, .L3+4
	and	r1, r1, r3
	orr	r1, r1, r2
	strh	r1, [r5]
	ldr	r2, .L3+8
	ldrb	r1, [r2]
	orr	r1, r1, r6
	mov	r3, r8
	and	r1, r1, r3
	strb	r1, [r2]
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, pc}
.L4:
	.align	2, 0
.L3:
	.word	x
	.word	-3969
	.word	y
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	x, 4	@ 4
	.comm	y, 4	@ 4
