@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	add	r4, r0, #0
	add	r5, r1, #0
	ldr	r0, .L3
	ldr	r1, .L3+4
	mov	r2, #200
	lsl	r2, r2, #1
	bl	memcpy
	add	r0, r4, #0
	add	r1, r5, #0
	mov	r2, #100
	bl	memcpy
	pop	{r4, r5, pc}
.L4:
	.align	2, 0
.L3:
	.word	a
	.word	b
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	a, 400	@ 400
	.comm	b, 400	@ 400
