@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
.LC4:
	.ascii	"\"hello\"\n\001\000"
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r1, .L3
	ldr	r0, .L3+4
	str	r0, [r1]
	ldr	r2, .L3+8
	ldr	r0, .L3+12		@ created by thumb_load_double_from_address
	ldr	r1, .L3+16		@ created by thumb_load_double_from_address
	str	r0, [r2]
	str	r1, [r2, #4]
	ldr	r2, .L3+20
	ldr	r0, .L3+24		@ created by thumb_load_double_from_address
	ldr	r1, .L3+28		@ created by thumb_load_double_from_address
	str	r0, [r2]
	str	r1, [r2, #4]
	ldr	r1, .L3+32
	ldr	r0, .L3+36
	str	r0, [r1]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	a
	.word 0x3f99999a	@ float 1.20000004768371582031e0
	.word	b
	.long 0x402a0000, 0x0	@ double 1.30000000000000000000e1
	.word	c
	.long 0x420a13b8, 0x60000000	@ double 1.40000000000000000000e10
	.word	d
	.word	.LC4
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	a, 4	@ 4
	.comm	b, 8	@ 8
	.comm	c, 8	@ 8
	.comm	d, 4	@ 4
