@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	ldr	r0, .L5
	ldr	r1, [r0]
	add	r2, r1, #0
	sub	r1, r1, #1
	str	r1, [r0]
	cmp	r2, #0
	ble	.L3	@cond_branch
	mov	r0, #6
	b	.L4
.L6:
	.align	2, 0
.L5:
	.word	glob
.L3:
	mov	r0, #4
.L4:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
