@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	add	r5, r1, #0
	add	r7, r2, #0
	add	r6, r3, #0
	ldr	r4, .L6
	bl	__fixsfsi
	str	r0, [r4]
	ldr	r4, .L6+4
	add	r0, r5, #0
	bl	__floatsisf
	str	r0, [r4]
	add	r6, r6, #3
	ldr	r1, .L6+8
	add	r0, r7, #0
	bl	__addsf3
	add	r7, r0, #0
	cmp	r6, #0
	blt	.L4	@cond_branch
	add	r0, r6, #0
	bl	__floatsisf
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	globali
	.word	globalf
	.word 0x40a00000	@ float 5.00000000000000000000e0
.L4:
	mov	r0, #1
	and	r0, r0, r6
	lsr	r1, r6, #1
	orr	r0, r0, r1
	bl	__floatsisf
	add	r1, r0, #0
	bl	__addsf3
.L5:
	add	r1, r0, #0
	add	r0, r1, #0
	add	r1, r7, #0
	bl	__addsf3
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	globali, 4	@ 4
	.comm	globalf, 4	@ 4
