@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	ldr	r4, .L5
	ldr	r1, [r4]
	ldr	r0, .L5+4
	str	r0, [r4]
	ldr	r5, .L5+8
	add	r0, r1, #0
	add	r1, r5, #0
	bl	__ltsf2
	cmp	r0, #0
	bge	.L3	@cond_branch
	ldr	r0, .L5+12
	str	r0, [r4]
.L3:
	ldr	r1, [r4]
	ldr	r0, .L5+16
	str	r0, [r4]
	add	r0, r1, #0
	add	r1, r5, #0
	bl	__ltsf2
	cmp	r0, #0
	blt	.L4	@cond_branch
	ldr	r0, .L5+20
	str	r0, [r4]
.L4:
	pop	{r4, r5, pc}
.L6:
	.align	2, 0
.L5:
	.word	x
	.word 0x40a00000	@ float 5.00000000000000000000e0
	.word 0x0	@ float 0.00000000000000000000e0
	.word 0x40c00000	@ float 6.00000000000000000000e0
	.word 0x40400000	@ float 3.00000000000000000000e0
	.word 0x40e00000	@ float 7.00000000000000000000e0
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	x, 4	@ 4
