@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	orr	r0, r0, r1
	mvn	r0, r0
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
