@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	add	r4, r0, #0
	cmp	r4, #3
	beq	.L5	@cond_branch
	cmp	r4, #3
	bgt	.L10	@cond_branch
	cmp	r4, #2
	beq	.L4	@cond_branch
	b	.L8
.L10:
	ldr	r5, .L12
	cmp	r4, #9
	beq	.L3	@cond_branch
	cmp	r4, #13
	beq	.L7	@cond_branch
	b	.L8
.L13:
	.align	2, 0
.L12:
	.word	glob
.L4:
	mov	r4, #1
.L5:
	ldr	r1, .L14
	ldr	r0, [r1]
	add	r0, r0, #1
	str	r0, [r1]
	add	r5, r1, #0
	b	.L3
.L15:
	.align	2, 0
.L14:
	.word	glob
.L7:
	mov	r4, #26
	b	.L3
.L8:
	lsr	r0, r4, #31
	add	r0, r4, r0
	asr	r4, r0, #1
	ldr	r5, .L16
.L3:
	ldr	r0, [r5]
	bl	test
	ldr	r0, [r5]
	cmp	r0, #0
	bne	.L11	@cond_branch
	str	r4, [r5]
.L11:
	mov	r0, #2
	pop	{r4, r5, pc}
.L17:
	.align	2, 0
.L16:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
