@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	static_fn
	.type	 static_fn,function
	.thumb_func
static_fn:
	bx	lr
.Lfe1:
	.size	 static_fn,.Lfe1-static_fn
.data
	.align	2, 0
	.type	 static_A_ptr,object
	.size	 static_A_ptr,4
static_A_ptr:
	.word	static_bss_A
	.align	2, 0
	.type	 static_A,object
	.size	 static_A,132
static_A:
	.byte	1
	.space	3
	.word	1
	.word	2
	.word	3
	.word	4
	.word	5
	.word 0x3f800000	@ float 1.00000000000000000000e0
	.word 0x40000000	@ float 2.00000000000000000000e0
	.word 0x40400000	@ float 3.00000000000000000000e0
	.word 0x40800000	@ float 4.00000000000000000000e0
	.word 0x40a00000	@ float 5.00000000000000000000e0
	.word 0x40c00000	@ float 6.00000000000000000000e0
	.word 0x40e00000	@ float 7.00000000000000000000e0
	.word 0x41000000	@ float 8.00000000000000000000e0
	.word 0x41100000	@ float 9.00000000000000000000e0
	.word 0x0	@ float 0.00000000000000000000e0
	.word 0x3f800000	@ float 1.00000000000000000000e0
	.word 0x40000000	@ float 2.00000000000000000000e0
	.word 0x3fc00000	@ float 1.50000000000000000000e0
	.word 0x40200000	@ float 2.50000000000000000000e0
	.word 0x40600000	@ float 3.50000000000000000000e0
	.word 0x40900000	@ float 4.50000000000000000000e0
	.word 0x40b00000	@ float 5.50000000000000000000e0
	.word 0x40d00000	@ float 6.50000000000000000000e0
	.word 0x40f00000	@ float 7.50000000000000000000e0
	.word 0x41080000	@ float 8.50000000000000000000e0
	.word 0x41180000	@ float 9.50000000000000000000e0
	.word 0x3f000000	@ float 5.00000000000000000000e-1
	.word 0x3fc00000	@ float 1.50000000000000000000e0
	.word 0x40200000	@ float 2.50000000000000000000e0
	.word	0
	.word	static_int
	.word	static_bss_A
	.align	2, 0
	.type	 static_array,object
	.size	 static_array,12
static_array:
	.word	2
	.word	4
	.word	6
	.align	1, 0
	.type	 unused_static_array,object
	.size	 unused_static_array,6
unused_static_array:
	.short	-8
	.short	10
	.short	12
	.align	2, 0
	.type	 unused_static_string,object
	.size	 unused_static_string,4
unused_static_string:
	.ascii	"abc\000"
	.section .rodata
	.align	2, 0
	.type	 static_ro_array,object
static_ro_array:
	.word	7
	.word	8
	.word	-9
	.size	 static_ro_array,12
	.align	2, 0
	.type	 unused_static_ro_array,object
unused_static_ro_array:
	.word	10
	.word	-11
	.word	12
	.size	 unused_static_ro_array,12
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	ldr	r5, .L4
	ldr	r1, [r5]
	lsl	r0, r1, #3
	sub	r0, r0, r1
	lsl	r0, r0, #3
	add	r0, r0, r1
	lsl	r0, r0, #3
	str	r0, [r5]
	ldr	r4, .L4+4
	ldr	r0, [r4]
	ldr	r1, .L4+8
	bl	__mulsf3
	str	r0, [r4]
	ldr	r0, .L4+12
	bl	static_fn
	ldr	r0, .L4+16
	ldr	r0, [r0]
	bl	extern_fn
	ldr	r2, .L4+20
	ldr	r0, .L4+24
	ldr	r1, .L4+28
	ldr	r0, [r0]
	ldr	r1, [r1]
	add	r0, r0, r1
	str	r0, [r2]
	ldr	r0, [r5]
	pop	{r4, r5, pc}
.L5:
	.align	2, 0
.L4:
	.word	static_int
	.word	extern_float
	.word 0x43e40000	@ float 4.56000000000000000000e2
	.word	static_A
	.word	static_A_ptr
	.word	static_bss_array
	.word	static_array
	.word	static_ro_array
.Lfe2:
	.size	 test,.Lfe2-test

	.lcomm	static_int,4

	.lcomm	static_bss_A,132

	.lcomm	static_bss_array,12
