@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r2, r0, #0
	cmp	r2, #1
	blt	.L15	@cond_branch
	cmp	r2, #4
	bgt	.L7	@cond_branch
	ldr	r1, .L29
	mov	r0, #1
	str	r0, [r1]
	cmp	r2, #1
	bne	.L3	@cond_branch
	b	.L27
.L30:
	.align	2, 0
.L29:
	.word	glob
.L7:
	cmp	r2, #6
	bgt	.L3	@cond_branch
	cmp	r2, #1
	bne	.L11	@cond_branch
	ldr	r0, .L31
	str	r2, [r0]
	b	.L3
.L32:
	.align	2, 0
.L31:
	.word	glob
.L11:
	ldr	r1, .L33
.L27:
	mov	r0, #2
	str	r0, [r1]
.L3:
	cmp	r2, #1
	blt	.L15	@cond_branch
	cmp	r2, #4
	bgt	.L19	@cond_branch
	ldr	r1, .L33
	mov	r0, #1
	str	r0, [r1]
	cmp	r2, #1
	bne	.L15	@cond_branch
	b	.L28
.L34:
	.align	2, 0
.L33:
	.word	glob
.L19:
	cmp	r2, #6
	bgt	.L15	@cond_branch
	cmp	r2, #1
	bne	.L23	@cond_branch
	ldr	r0, .L35
	str	r2, [r0]
	b	.L15
.L36:
	.align	2, 0
.L35:
	.word	glob
.L23:
	ldr	r1, .L37
.L28:
	mov	r0, #2
	str	r0, [r1]
.L15:
	pop	{pc}
.L38:
	.align	2, 0
.L37:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
