@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	ldr	r1, .L8
	ldr	r0, [r1]
	cmp	r0, #2
	beq	.L4	@cond_branch
	add	r0, r1, #0
	mov	r1, #1
.L6:
	str	r1, [r0]
	b	.L6
.L9:
	.align	2, 0
.L8:
	.word	x
.L4:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	x, 4	@ 4
