@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	add	sp, sp, #-8
	str	r0, [sp, #4]
	str	r1, [sp]
	mov	r0, #1
	neg	r0, r0
	add	sp, sp, #8
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
