@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	ldr	r6, .L9+4		@ created by thumb_load_double_from_address
	ldr	r5, .L9		@ created by thumb_load_double_from_address
	add	r4, r0, #0
	cmp	r4, #0
	beq	.L4	@cond_branch
.L6:
	add	r0, r4, #0
	bl	__floatsidf
	add	r3, r1, #0
	add	r2, r0, #0
	cmp	r4, #0
	bge	.L7	@cond_branch
	ldr	r2, .L9+8		@ created by thumb_load_double_from_address
	ldr	r3, .L9+12		@ created by thumb_load_double_from_address
	bl	__adddf3
	add	r3, r1, #0
	add	r2, r0, #0
.L7:
	add	r1, r6, #0
	add	r0, r5, #0
	bl	__muldf3
	add	r6, r1, #0
	add	r5, r0, #0
	sub	r4, r4, #1
	cmp	r4, #0
	bne	.L6	@cond_branch
.L4:
	add	r1, r6, #0
	add	r0, r5, #0
	bl	__truncdfsf2
	pop	{r4, r5, r6, pc}
.L10:
	.align	2, 0
.L9:
	.long 0x3ff00000, 0x0	@ double 1.00000000000000000000e0
	.long 0x41f00000, 0x0	@ double 4.29496729600000000000e9
.Lfe1:
	.size	 test,.Lfe1-test
