@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	add	r4, r1, #0
	ldr	r5, [sp, #16]
	mov	r0, #0
.L4:
	add	r1, r4, #0
	add	r2, r5, #0
	bl	foo
	b	.L4
.Lfe2:
	.size	 test,.Lfe2-test
