@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	add	r4, r1, #0
	add	r1, r2, #0
	mov	r8, r3
	ldr	r5, [sp, #24]
	ldr	r7, [sp, #28]
	ldr	r6, .L3
	bl	__addsf3
	add	r1, r5, #0
	bl	__addsf3
	str	r0, [r6]
	ldr	r0, .L3+4
	add	r4, r4, r8
	add	r4, r4, r7
	str	r4, [r0]
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7, pc}
.L4:
	.align	2, 0
.L3:
	.word	globalf
	.word	globali
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	globali, 4	@ 4
	.comm	globalf, 4	@ 4
