@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	add	r5, r1, #0
	add	r6, r2, #0
	add	r7, r3, #0
	ldr	r4, .L6
	bl	__fixsfsi
	str	r0, [r4]
	ldr	r4, .L6+4
	add	r0, r5, #0
	bl	__floatsisf
	str	r0, [r4]
	add	r7, r7, #3
	add	r0, r6, #0
	bl	__extendsfdf2
	ldr	r2, .L6+8		@ created by thumb_load_double_from_address
	ldr	r3, .L6+12		@ created by thumb_load_double_from_address
	bl	__adddf3
	bl	__truncdfsf2
	add	r6, r0, #0
	bl	__extendsfdf2
	ldr	r2, .L6+16		@ created by thumb_load_double_from_address
	ldr	r3, .L6+20		@ created by thumb_load_double_from_address
	bl	__adddf3
	bl	__truncdfsf2
	add	r6, r0, #0
	ldr	r1, .L6+24
	bl	__addsf3
	add	r6, r0, #0
	bl	__extendsfdf2
	ldr	r2, .L6+28		@ created by thumb_load_double_from_address
	ldr	r3, .L6+32		@ created by thumb_load_double_from_address
	bl	__adddf3
	bl	__truncdfsf2
	add	r6, r0, #0
	cmp	r7, #0
	blt	.L4	@cond_branch
	add	r0, r7, #0
	bl	__floatsisf
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	globali
	.word	globalf
	.long 0x40140000, 0x0	@ double 5.00000000000000000000e0
	.long 0x0, 0x0	@ double 0.00000000000000000000e0
	.word 0x0	@ float 0.00000000000000000000e0
	.long 0x40153333, 0x33333333	@ double 5.29999999999999982236e0
.L4:
	mov	r0, #1
	and	r0, r0, r7
	lsr	r1, r7, #1
	orr	r0, r0, r1
	bl	__floatsisf
	add	r1, r0, #0
	bl	__addsf3
.L5:
	add	r1, r0, #0
	add	r0, r1, #0
	add	r1, r6, #0
	bl	__addsf3
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	globali, 4	@ 4
	.comm	globalf, 4	@ 4
