@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	ldr	r4, .L3
	lsl	r3, r1, #2
	add	r2, r0, #4
	add	r2, r2, r3
	ldr	r2, [r2]
	str	r2, [r4]
	add	r3, r3, #4
	add	r3, r0, r3
	str	r3, [r4]
	lsl	r3, r1, #3
	add	r2, r0, #0
	add	r2, r2, #48
	add	r2, r2, r3
	ldr	r2, [r2]
	str	r2, [r4]
	add	r3, r3, r0
	add	r3, r3, #48
	str	r3, [r4]
	lsl	r1, r1, #7
	add	r1, r1, r0
	ldr	r1, [r1, #124]
	str	r1, [r4]
	ldr	r1, [r0, #72]
	str	r1, [r4]
	add	r0, r0, #72
	str	r0, [r4]
	pop	{r4, pc}
.L4:
	.align	2, 0
.L3:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
