@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r2, .L3
	ldr	r1, .L3+4
	add	r0, r0, r1
	ldr	r1, [r0]
	str	r1, [r2]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	glob
	.word	74568
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
