@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	cmp	r0, #0
	bne	.L4	@cond_branch
	cmp	r1, #0
	beq	.L3	@cond_branch
.L4:
	cmp	r2, #0
	bne	.L5	@cond_branch
	cmp	r3, #0
	beq	.L3	@cond_branch
.L5:
	add	r0, r0, r1
	b	.L7
.L3:
	add	r0, r2, r3
.L7:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
