@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	frob
	.type	 frob,function
	.thumb_func
frob:
	bx	lr
.Lfe1:
	.size	 frob,.Lfe1-frob
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	add	sp, sp, #-24
	add	r7, r0, #0
	add	r4, sp, #12
	add	r0, r4, #0
	bl	frob
	mov	r6, sp
	add	r6, r6, #14
	add	r0, r6, #0
	bl	frob
	add	r0, sp, #16
	bl	frob
	add	r0, sp, #20
	bl	frob
	mov	r0, sp
	bl	frob
	ldr	r1, [r7]
	ldr	r3, [r7, #4]
	add	r0, r1, r3
	strb	r0, [r4]
	ldr	r2, [r7, #8]
	add	r0, r1, r2
	strh	r0, [r6]
	add	r5, r3, r2
	str	r5, [sp, #16]
	ldrb	r0, [r4]
	mul	r0, r0, r1
	str	r0, [sp]
	mov	r1, #0
	ldrsh	r0, [r6, r1]
	mul	r0, r0, r3
	str	r0, [sp, #4]
	mov	r0, r2
	mul	r0, r0, r5
	str	r0, [sp, #8]
	ldrb	r0, [r4]
	cmp	r0, #0
	beq	.L4	@cond_branch
	str	r7, [sp, #20]
	b	.L5
.L4:
	mov	r0, sp
	str	r0, [sp, #20]
.L5:
	mov	r1, #0
	ldrsh	r0, [r6, r1]
	ldrb	r4, [r4]
	add	r0, r0, r4
	ldr	r1, [sp, #16]
	add	r0, r0, r1
	ldr	r1, [sp, #20]
	ldr	r1, [r1]
	add	r0, r0, r1
	ldr	r1, [sp, #4]
	add	r0, r0, r1
	add	sp, sp, #24
	pop	{r4, r5, r6, r7, pc}
.Lfe2:
	.size	 test,.Lfe2-test
