@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r3, r0, #0
	mov	r2, #0
	ldr	r1, .L13
	b	.L3
.L14:
	.align	2, 0
.L13:
	.word	globals
.L9:
	ldr	r0, [r1, #20]
	cmp	r0, #2
	bne	.L10	@cond_branch
	mov	r0, #3
	str	r0, [r1, #24]
	b	.L5
.L10:
	mov	r0, #4
.L12:
	str	r0, [r1, #12]
.L5:
	add	r2, r2, #1
.L3:
	cmp	r2, r3
	bge	.L4	@cond_branch
	mov	r0, #1
	str	r0, [r1]
	ldr	r0, [r1, #4]
	cmp	r0, #2
	bne	.L7	@cond_branch
	mov	r0, #3
	str	r0, [r1, #8]
	b	.L4
.L7:
	ldr	r0, [r1, #8]
	cmp	r0, #2
	bne	.L8	@cond_branch
	mov	r0, #3
	b	.L12
.L8:
	ldr	r0, [r1, #16]
	cmp	r0, #2
	bne	.L9	@cond_branch
	mov	r0, #3
	str	r0, [r1, #20]
.L4:
	mov	r0, #5
	str	r0, [r1, #16]
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	globals, 40	@ 40
