@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
.LC0:
	.ascii	"hello\000"
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-8
	add	r4, r0, #0
	add	r5, r1, #0
	add	r6, r2, #0
	ldr	r1, .L3
	mov	r0, sp
	mov	r2, #6
	bl	memcpy
	mov	r1, sp
	add	r0, r1, r4
	ldrb	r1, [r0]
	lsl	r2, r4, #2
	add	r5, r2, r5
	ldr	r0, [r5]
	mul	r0, r0, r1
	ldr	r1, .L3+4
	lsl	r4, r4, #1
	add	r4, r4, r1
	mov	r3, #0
	ldrsh	r1, [r4, r3]
	add	r0, r0, r1
	add	r6, r6, #4
	add	r6, r6, r2
	ldr	r1, [r6]
	add	r0, r0, r1
	add	sp, sp, #8
	pop	{r4, r5, r6, pc}
.L4:
	.align	2, 0
.L3:
	.word	.LC0
	.word	globalArray
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	globalArray, 12	@ 10
