@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	ldr	r1, .L6
	mov	r0, #1
.L3:
	str	r0, [r1]
	b	.L3
.L7:
	.align	2, 0
.L6:
	.word	x
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	x, 4	@ 4
