@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	add	sp, sp, #-4
	add	r5, r0, #0
	add	r3, r1, #0
	ldr	r0, .L5
	ldr	r1, [r0]
	lsl	r2, r5, #3
	add	r0, r1, #4
	add	r0, r0, r2
	ldr	r0, [r0]
	add	r6, r0, #1
	add	r1, r1, #8
	add	r1, r1, r2
	ldr	r7, [r1]
	str	r5, [sp]
	mov	r0, #1
	mov	r1, #2
	add	r2, r6, #0
	bl	foo
	add	r4, r0, #0
	cmp	r4, #0
	beq	.L3	@cond_branch
	add	r0, r7, #0
	add	r1, r4, #0
	add	r2, r6, #0
	bl	bar
	ldr	r0, .L5+4
	add	r0, r5, r0
	mov	r1, #5
	strb	r1, [r0]
	add	r0, r4, #0
	b	.L4
.L6:
	.align	2, 0
.L5:
	.word	global
	.word	global2
.L3:
	mov	r0, #0
.L4:
	add	sp, sp, #4
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	mov	r0, #1
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
	.align	2, 0
	.globl	bar
	.type	 bar,function
	.thumb_func
bar:
	mov	r0, #1
	bx	lr
.Lfe3:
	.size	 bar,.Lfe3-bar
	.comm	global, 4	@ 4
	.comm	global2, 100	@ 100
