@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	lsl	r2, r2, #16
	lsr	r2, r2, #16
	mov	r3, #2
	strh	r3, [r0, #8]
	strh	r1, [r0, #10]
	strh	r2, [r0, #12]
	lsl	r2, r2, #16
	asr	r2, r2, #16
	add	r2, r2, r1
	strh	r2, [r0, #14]
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
