@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	ldr	r5, .L7
	ldr	r7, .L7+4
	ldr	r0, [r7]
	bl	__fixunssfsi
	str	r0, [r5]
	ldr	r6, .L7+8
	ldr	r0, [r6]		@ created by thumb_load_double_from_address
	ldr	r1, [r6, #4]		@ created by thumb_load_double_from_address
	bl	__fixunsdfsi
	str	r0, [r5]
	ldr	r4, [r5]
	add	r0, r4, #0
	bl	__floatsidf
	cmp	r4, #0
	bge	.L3	@cond_branch
	ldr	r2, .L7+12		@ created by thumb_load_double_from_address
	ldr	r3, .L7+16		@ created by thumb_load_double_from_address
	bl	__adddf3
.L3:
	str	r0, [r6]
	str	r1, [r6, #4]
	add	r4, r7, #0
	ldr	r1, [r5]
	cmp	r1, #0
	blt	.L5	@cond_branch
	add	r0, r1, #0
	bl	__floatsisf
	b	.L6
.L8:
	.align	2, 0
.L7:
	.word	u
	.word	flt
	.word	dbl
	.long 0x41f00000, 0x0	@ double 4.29496729600000000000e9
.L5:
	mov	r0, #1
	and	r0, r0, r1
	lsr	r1, r1, #1
	orr	r0, r0, r1
	bl	__floatsisf
	add	r1, r0, #0
	bl	__addsf3
.L6:
	add	r1, r0, #0
	str	r1, [r4]
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	flt, 4	@ 4
	.comm	dbl, 8	@ 8
	.comm	u, 4	@ 4
