@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	ldr	r4, .L3
	ldr	r1, [r4]
	add	r0, r1, #0
	bl	__addsf3
	str	r0, [r4]
	ldr	r4, .L3+4
	ldr	r2, [r4]		@ created by thumb_load_double_from_address
	ldr	r3, [r4, #4]		@ created by thumb_load_double_from_address
	add	r1, r3, #0
	add	r0, r2, #0
	bl	__adddf3
	str	r0, [r4]
	str	r1, [r4, #4]
	pop	{r4, pc}
.L4:
	.align	2, 0
.L3:
	.word	x
	.word	y
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	x, 4	@ 4
	.comm	y, 8	@ 8
