@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r2, r0, #0
	sub	r0, r2, #1
	cmp	r0, #6
	bhi	.L10	@cond_branch
	lsl	r0, r0, #2
	ldr	r1, .L13
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L14:
	.align	2, 0
.L13:
	.word	.L11
	.align	2, 0
	.align	2, 0
.L11:
	.word	.L4
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L10
	.word	.L9
	.word	.L9
.L4:
	mov	r0, r2
	mul	r0, r0, r2
	b	.L12
.L5:
	sub	r2, r2, #1
.L6:
	lsl	r0, r2, #1
	b	.L12
.L7:
	add	r2, r2, #1
	b	.L3
.L9:
	lsl	r2, r2, #1
	b	.L3
.L10:
	lsr	r0, r2, #31
	add	r0, r2, r0
	asr	r2, r0, #1
.L3:
	ldr	r0, .L15
	str	r2, [r0]
	mov	r0, #2
.L12:
	pop	{pc}
.L16:
	.align	2, 0
.L15:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
