@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	lsl	r3, r2, #2
	add	r0, r0, r3
	lsl	r2, r2, #3
	add	r1, r1, #8
	add	r1, r1, r2
	ldr	r0, [r0, #4]
	ldr	r1, [r1]
	add	r0, r0, r1
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
