.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.39.0 */

nonmatching test, 0x20

glabel test # 0
    /* 0000B0 000000B0 000670C0 */  sll         $t6, $a2, 3
    /* 0000B4 000000B4 0006C880 */  sll         $t9, $a2, 2
    /* 0000B8 000000B8 00994021 */  addu        $t0, $a0, $t9
    /* 0000BC 000000BC 00AE7821 */  addu        $t7, $a1, $t6
    /* 0000C0 000000C0 8DF80008 */  lw          $t8, 0x8($t7)
    /* 0000C4 000000C4 8D090004 */  lw          $t1, 0x4($t0)
    /* 0000C8 000000C8 03E00008 */  jr          $ra
    /* 0000CC 000000CC 03091021 */   addu       $v0, $t8, $t1
endlabel test
