@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	r4, r0, #0
	b	.L3
.L6:
	add	r0, r4, #0
	bl	foo
	add	r4, r4, #1
.L3:
	add	r0, r4, #0
	bl	foo
	lsl	r4, r4, #1
	cmp	r4, #3
	ble	.L6	@cond_branch
	add	r0, r4, #0
	pop	{r4, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
