@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	ldr	r1, [r1]
	str	r1, [r0]
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	sp, sp, #-8
	mov	r0, sp
	str	r0, [sp]
	add	r1, sp, #4
	str	r1, [sp, #4]
	bl	foo
	ldr	r1, [sp, #4]
	str	r1, [sp]
	add	r0, r1, #0
	bl	foo
	add	sp, sp, #8
	pop	{pc}
.Lfe2:
	.size	 test,.Lfe2-test
