@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	mov	r3, #0
	mov	r5, #0
	cmp	r5, r0
	bge	.L4	@cond_branch
.L5:
	add	r4, r3, #1
	cmp	r0, #0
	ble	.L7	@cond_branch
	mov	r2, #0
	add	r1, r0, #0
.L8:
	add	r5, r5, r2
	add	r2, r2, r3
	sub	r1, r1, #1
	cmp	r1, #0
	bne	.L8	@cond_branch
.L7:
	add	r3, r4, #0
	cmp	r3, r0
	blt	.L5	@cond_branch
.L4:
	add	r0, r5, #0
	pop	{r4, r5, pc}
.Lfe1:
	.size	 test,.Lfe1-test
