@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	func_00400090
	.type	 func_00400090,function
	.thumb_func
func_00400090:
	bx	lr
.Lfe1:
	.size	 func_00400090,.Lfe1-func_00400090
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	sp, sp, #-12
	add	r2, r0, #0
	ldrb	r1, [r2]
	mov	r0, sp
	strb	r1, [r0]
	add	r0, r2, #0
	add	r0, r0, #40
	str	r0, [sp, #4]
	mov	r1, #200
	lsl	r1, r1, #1
	add	r0, r2, r1
	ldr	r0, [r0]
	str	r0, [sp, #8]
	mov	r4, sp
	mov	r0, sp
	bl	func_00400090
	mov	r1, sp
	ldrb	r0, [r0]
	ldrb	r1, [r1]
	add	r0, r0, r1
	strb	r0, [r4]
	add	r0, sp, #4
	bl	func_00400090
	str	r0, [sp, #4]
	add	r0, sp, #8
	bl	func_00400090
	ldr	r2, [sp, #8]
	ldr	r0, [r0]
	add	r2, r2, r0
	str	r2, [sp, #8]
	mov	r0, sp
	ldrb	r0, [r0]
	ldr	r1, [sp, #4]
	ldr	r1, [r1]
	add	r0, r0, r1
	add	r0, r0, r2
	add	sp, sp, #12
	pop	{r4, pc}
.Lfe2:
	.size	 test,.Lfe2-test
