@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	ldr	r1, .L9
	ldr	r0, [r1]
	mov	r4, #1
	and	r0, r0, r4
	cmp	r0, #0
	beq	.L3	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L3:
	ldr	r0, [r1]
	mov	r3, #128
	lsl	r3, r3, #9
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L4	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L4:
	ldr	r0, [r1]
	mov	r2, #128
	lsl	r2, r2, #24
	cmp	r0, #0
	bge	.L5	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L5:
	ldr	r0, [r1]
	and	r0, r0, r4
	cmp	r0, #0
	beq	.L6	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L6:
	ldr	r0, [r1]
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L7	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L7:
	ldr	r0, [r1]
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L8	@cond_branch
	mov	r0, #0
	str	r0, [r1]
.L8:
	pop	{r4, pc}
.L10:
	.align	2, 0
.L9:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
