@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	ldr	r0, [r0]
	cmp	r0, #8
	beq	.L4	@cond_branch
	cmp	r0, #15
	beq	.L5	@cond_branch
	b	.L3
.L4:
	ldr	r0, [r1]
	add	r0, r0, #8
	b	.L8
.L5:
	ldr	r0, [r1]
	sub	r0, r0, #15
.L8:
	str	r0, [r1]
.L3:
	mov	r0, #0
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
