@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r2, r0, #0
	add	r0, r1, #0
	bl	_call_via_r2
	add	r0, r0, #1
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
