@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.data
	.align	2, 0
	.type	 D_410150,object
	.size	 D_410150,4
D_410150:
	.word 0x3f9d70a4	@ float 1.23000001907348632812e0
	.align	2, 0
	.type	 D_410154,object
	.size	 D_410154,12
D_410154:
	.word 0x40400000	@ float 3.00000000000000000000e0
	.word 0x40800000	@ float 4.00000000000000000000e0
	.word 0x40a00000	@ float 5.00000000000000000000e0
	.align	2, 0
	.type	 D_410160,object
D_410160:
	.word 0x40c00000	@ float 6.00000000000000000000e0
	.word 0x40e00000	@ float 7.00000000000000000000e0
	.word 0x41000000	@ float 8.00000000000000000000e0
	.size	 D_410160,12
	.section .rodata
	.align	2, 0
	.type	 D_400120,object
	.size	 D_400120,12
D_400120:
	.word 0x41200000	@ float 1.00000000000000000000e1
	.word 0x41300000	@ float 1.10000000000000000000e1
	.word 0x41400000	@ float 1.20000000000000000000e1
	.align	2, 0
	.type	 D_40012C,object
D_40012C:
	.word 0x41600000	@ float 1.40000000000000000000e1
	.word 0x41700000	@ float 1.50000000000000000000e1
	.word 0x41800000	@ float 1.60000000000000000000e1
	.word 0x41880000	@ float 1.70000000000000000000e1
	.word 0x41900000	@ float 1.80000000000000000000e1
	.size	 D_40012C,20
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	ldr	r5, .L3
	lsl	r4, r4, #2
	add	r5, r4, r5
	ldr	r0, .L3+4
	add	r0, r4, r0
	ldr	r1, .L3+8
	add	r1, r4, r1
	ldr	r0, [r0]
	ldr	r1, [r1]
	bl	__addsf3
	add	r6, r0, #0
	str	r6, [r5]
	ldr	r5, .L3+12
	ldr	r1, .L3+16
	bl	__mulsf3
	ldr	r1, .L3+20
	add	r4, r4, r1
	ldr	r1, [r4]
	bl	__addsf3
	add	r1, r0, #0
	ldr	r0, [r5]
	bl	__mulsf3
	str	r0, [r5]
	add	r1, r6, #0
	bl	__divsf3
	pop	{r4, r5, r6, pc}
.L4:
	.align	2, 0
.L3:
	.word	D_410170
	.word	D_410160
	.word	D_400120
	.word	D_410150
	.word 0x40b570a4	@ float 5.67000007629394531250e0
	.word	D_40012C
.Lfe1:
	.size	 test,.Lfe1-test

	.lcomm	D_410170,12
