@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r1, .L3
	ldr	r0, .L3+4
	ldrb	r0, [r0, #0]
	lsl	r0, r0, #24
	asr	r0, r0, #24
	str	r0, [r1]
	ldr	r0, .L3+8
	ldrb	r0, [r0]
	str	r0, [r1, #4]
	ldr	r0, .L3+12
	mov	r2, #0
	ldrsh	r0, [r0, r2]
	str	r0, [r1, #8]
	ldr	r0, .L3+16
	ldrh	r0, [r0]
	str	r0, [r1, #12]
	ldr	r0, .L3+20
	ldr	r0, [r0]
	str	r0, [r1, #16]
	ldr	r0, .L3+24
	ldr	r0, [r0]
	str	r0, [r1, #20]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	ar
	.word	a
	.word	b
	.word	c
	.word	d
	.word	e
	.word	f
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	a, 4	@ 1
	.comm	b, 4	@ 1
	.comm	c, 4	@ 2
	.comm	d, 4	@ 2
	.comm	e, 4	@ 4
	.comm	f, 4	@ 4
	.comm	ar, 24	@ 24
