@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	bl	blahf
	bl	__extendsfdf2
	bl	blah
	bl	__truncdfsf2
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	blahf
	.type	 blahf,function
	.thumb_func
blahf:
	bx	lr
.Lfe2:
	.size	 blahf,.Lfe2-blahf
	.align	2, 0
	.globl	blah
	.type	 blah,function
	.thumb_func
blah:
	bx	lr
.Lfe3:
	.size	 blah,.Lfe3-blah
