@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r1, r0, #0
	mov	r0, #0
.L9:
	cmp	r0, r1
	bge	.L4	@cond_branch
	cmp	r0, #5
	bne	.L6	@cond_branch
	mov	r0, #10
	b	.L9
.L6:
	add	r0, r0, #4
	b	.L9
.L4:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
