@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	bl	foo
	ldr	r2, .L3
	mov	r1, #1
	str	r1, [r2]
	bl	bar
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	global
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	mov	r0, #1
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
	.align	2, 0
	.globl	bar
	.type	 bar,function
	.thumb_func
bar:
	bx	lr
.Lfe3:
	.size	 bar,.Lfe3-bar
	.comm	global, 4	@ 4
