@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	add	r5, r2, #0
	add	r0, r1, r5
	mov	r6, #0
	cmn	r4, r1
	bne	.L4	@cond_branch
	cmp	r0, #0
	beq	.L5	@cond_branch
	mov	r0, r4
	mul	r0, r0, r1
	cmp	r0, #0
	bne	.L4	@cond_branch
.L5:
	cmp	r3, #0
	beq	.L3	@cond_branch
	add	r2, r4, #1
	cmp	r4, #0
	beq	.L11	@cond_branch
.L4:
	mov	r6, #1
.L3:
	add	r2, r4, #1
	cmp	r4, #0
	beq	.L11	@cond_branch
	cmp	r1, #0
	bne	.L7	@cond_branch
	cmp	r5, #0
	beq	.L6	@cond_branch
.L7:
	add	r2, r4, #1
	cmp	r3, #0
	bne	.L8	@cond_branch
	cmp	r2, #0
	beq	.L6	@cond_branch
.L8:
	mov	r6, #2
.L6:
	cmp	r4, #0
	beq	.L11	@cond_branch
	cmp	r3, #0
	bne	.L10	@cond_branch
.L11:
	cmp	r1, #0
	bne	.L12	@cond_branch
	cmp	r5, #0
	beq	.L9	@cond_branch
.L12:
	cmp	r2, #0
	beq	.L9	@cond_branch
.L10:
	mov	r6, #3
.L9:
	cmp	r4, #0
	beq	.L32	@cond_branch
	cmp	r1, #0
	beq	.L13	@cond_branch
	cmp	r5, #0
	bne	.L14	@cond_branch
	cmp	r3, #0
	beq	.L13	@cond_branch
.L14:
	cmp	r2, #0
	bne	.L15	@cond_branch
	add	r0, r1, #1
	cmp	r0, #0
	beq	.L13	@cond_branch
.L15:
	mov	r6, #4
.L13:
	cmp	r4, #0
	bne	.L19	@cond_branch
.L32:
	cmp	r1, #0
	beq	.L18	@cond_branch
.L19:
	cmp	r5, #0
	bne	.L17	@cond_branch
.L18:
	cmp	r3, #0
	beq	.L20	@cond_branch
	cmp	r2, #0
	bne	.L17	@cond_branch
.L20:
	add	r0, r1, #1
	cmp	r0, #0
	bne	.L17	@cond_branch
	add	r0, r5, #1
	cmp	r0, #0
	beq	.L16	@cond_branch
.L17:
	mov	r6, #5
.L16:
	cmp	r4, #0
	beq	.L23	@cond_branch
	cmp	r1, #0
	bne	.L22	@cond_branch
.L23:
	cmp	r5, #0
	beq	.L21	@cond_branch
	cmp	r3, #0
	beq	.L21	@cond_branch
.L22:
	cmp	r2, #0
	bne	.L24	@cond_branch
	add	r0, r1, #1
	cmp	r0, #0
	beq	.L21	@cond_branch
.L24:
	mov	r6, #6
.L21:
	cmp	r4, #0
	beq	.L33	@cond_branch
	cmp	r1, #0
	beq	.L26	@cond_branch
	cmp	r5, r2
	beq	.L27	@cond_branch
	b	.L25
.L26:
	cmp	r3, r2
	bne	.L25	@cond_branch
.L27:
	add	r0, r1, #1
	cmp	r0, #0
	beq	.L25	@cond_branch
	mov	r6, #7
.L25:
	cmp	r4, #0
	bne	.L29	@cond_branch
.L33:
	cmp	r1, #0
	beq	.L30	@cond_branch
	cmp	r5, r2
	beq	.L29	@cond_branch
	b	.L31
.L30:
	cmp	r3, r2
	beq	.L29	@cond_branch
.L31:
	add	r0, r1, #1
	cmp	r0, #0
	beq	.L28	@cond_branch
.L29:
	mov	r6, #8
.L28:
	add	r0, r6, #0
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 test,.Lfe1-test
