@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	cmp	r0, #0
	bne	.L3	@cond_branch
	mov	r0, #0
	b	.L5
.L3:
	mov	r0, #1
.L5:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
