@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	ldr	r3, .L5
	mov	r2, #0
	cmp	r0, r1
	bcs	.L3	@cond_branch
	mov	r2, #1
.L3:
	str	r2, [r3]
	mov	r2, #0
	cmp	r0, r1
	bhi	.L4	@cond_branch
	mov	r2, #1
.L4:
	str	r2, [r3]
	pop	{pc}
.L6:
	.align	2, 0
.L5:
	.word	global
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	global, 4	@ 4
