.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching test, 0x20

glabel test # 0
    /* 000100 00000100 3C020000 */  lui         $v0, %hi(global)
    /* 000104 00000104 24420000 */  addiu       $v0, $v0, %lo(global)
    /* 000108 00000108 0085702B */  sltu        $t6, $a0, $a1
    /* 00010C 0000010C 00A4782B */  sltu        $t7, $a1, $a0
    /* 000110 00000110 AC4E0000 */  sw          $t6, 0x0($v0)
    /* 000114 00000114 39EF0001 */  xori        $t7, $t7, 0x1
    /* 000118 00000118 03E00008 */  jr          $ra
    /* 00011C 0000011C AC4F0000 */   sw         $t7, 0x0($v0)
endlabel test
.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching global, 0x4

dlabel global
    /* 00000120 */ .space 0x04

nonmatching B_00000124, 0xC

/* Automatically generated and unreferenced pad */
dlabel B_00000124
    /* 00000124 */ .space 0x0C
