.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching test, 0x2C

glabel test # 0
    /* 000100 00000100 0085702B */  sltu        $t6, $a0, $a1
    /* 000104 00000104 3C010000 */  lui         $at, %hi(global)
    /* 000108 00000108 AC2E0000 */  sw          $t6, %lo(global)($at)
    /* 00010C 0000010C 00A4782B */  sltu        $t7, $a1, $a0
    /* 000110 00000110 39EF0001 */  xori        $t7, $t7, 0x1
    /* 000114 00000114 3C010000 */  lui         $at, %hi(global)
    /* 000118 00000118 AC2F0000 */  sw          $t7, %lo(global)($at)
    /* 00011C 0000011C 03E00008 */  jr          $ra
    /* 000120 00000120 00000000 */   nop
    /* 000124 00000124 03E00008 */  jr          $ra
    /* 000128 00000128 00000000 */   nop
endlabel test
    /* 00012C 0000012C 00000000 */  nop
.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching global, 0x4

dlabel global
    /* 00000130 */ .space 0x04

nonmatching B_00000134, 0xC

/* Automatically generated and unreferenced pad */
dlabel B_00000134
    /* 00000134 */ .space 0x0C
