@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	add	r0, r0, #1
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	add	r7, r0, #0
	mov	r8, r2
	add	r6, r3, #0
	add	r5, r7, r1
	add	r0, r1, r2
	cmp	r5, #0
	bne	.L5	@cond_branch
	cmp	r0, #0
	bne	.L5	@cond_branch
	mov	r0, #0
	bl	foo
	cmp	r0, #0
	bne	.L5	@cond_branch
	mov	r5, #2
	cmp	r6, #0
	beq	.L4	@cond_branch
.L5:
	mov	r4, #1
	b	.L6
.L4:
	mov	r4, #2
	neg	r4, r4
	cmp	r7, #0
	beq	.L6	@cond_branch
	add	r4, r4, #1
.L6:
	add	r4, r4, r8
	cmp	r5, #0
	beq	.L14	@cond_branch
	cmp	r0, #0
	beq	.L9	@cond_branch
	add	r5, r5, r0
	add	r0, r5, #0
	bl	foo
	cmp	r0, #0
	beq	.L9	@cond_branch
	cmp	r6, #0
	beq	.L9	@cond_branch
	cmp	r4, #4
	bgt	.L11	@cond_branch
.L12:
	add	r4, r4, #1
	lsl	r4, r4, #1
	cmp	r4, #4
	ble	.L12	@cond_branch
.L11:
	add	r4, r4, #5
.L9:
	cmp	r5, #0
	beq	.L14	@cond_branch
	cmp	r0, #0
	beq	.L14	@cond_branch
	add	r5, r5, r0
	add	r0, r5, #0
	bl	foo
	cmp	r0, #0
	beq	.L14	@cond_branch
	cmp	r6, #0
	beq	.L14	@cond_branch
	cmp	r4, #4
	bgt	.L16	@cond_branch
.L17:
	add	r4, r4, #1
	lsl	r4, r4, #1
	cmp	r4, #4
	ble	.L17	@cond_branch
.L16:
	add	r4, r4, #5
	b	.L19
.L14:
	add	r4, r4, #6
.L19:
	add	r0, r4, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7, pc}
.Lfe2:
	.size	 test,.Lfe2-test
