@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r2, [r0]
	ldr	r3, [r0, #4]
	add	r2, r2, r3
	str	r2, [r0, #4]
	ldr	r2, [r0]		@ created by thumb_load_double_from_address
	ldr	r3, [r0, #4]		@ created by thumb_load_double_from_address
	str	r2, [r1]
	str	r3, [r1, #4]
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
