@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r2, [r0]
	lsr	r1, r2, #31
	add	r1, r2, r1
	asr	r1, r1, #1
	lsl	r1, r1, #1
	sub	r1, r2, r1
	str	r1, [r0]
	bx	lr
.Lfe1:
	.size	 test,.Lfe1-test
