@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	ldr	r2, .L3
	str	r0, [r2]
	lsl	r3, r0, #1
	str	r3, [r2]
	add	r3, r3, r0
	str	r3, [r2]
	lsl	r5, r0, #2
	str	r5, [r2]
	add	r5, r5, r0
	str	r5, [r2]
	lsl	r1, r3, #1
	str	r1, [r2]
	lsl	r4, r0, #3
	sub	r6, r4, r0
	str	r6, [r2]
	str	r4, [r2]
	add	r4, r4, r0
	str	r4, [r2]
	lsl	r1, r5, #1
	str	r1, [r2]
	mov	r1, #11
	mul	r1, r1, r0
	str	r1, [r2]
	lsl	r3, r3, #2
	str	r3, [r2]
	mov	r1, #13
	mul	r1, r1, r0
	str	r1, [r2]
	lsl	r6, r6, #1
	str	r6, [r2]
	lsl	r1, r0, #4
	sub	r3, r1, r0
	str	r3, [r2]
	str	r1, [r2]
	add	r1, r1, r0
	str	r1, [r2]
	lsl	r4, r4, #1
	str	r4, [r2]
	lsl	r5, r5, #2
	sub	r1, r5, r0
	str	r1, [r2]
	str	r5, [r2]
	add	r5, r5, r0
	str	r5, [r2]
	mov	r1, #22
	mul	r0, r0, r1
	str	r0, [r2]
	pop	{r4, r5, r6, pc}
.L4:
	.align	2, 0
.L3:
	.word	y
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	y, 4	@ 4
