@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.type	 read,function
	.thumb_func
read:
	add	r0, r2, #0
	bx	lr
.Lfe1:
	.size	 read,.Lfe1-read
	.align	2, 0
	.type	 write,function
	.thumb_func
write:
	add	r0, r2, #0
	bx	lr
.Lfe2:
	.size	 write,.Lfe2-write
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	ldr	r4, .L7
	add	sp, sp, r4
	add	r4, r1, #0
	ldr	r3, .L7+4
	mov	r1, sp
	add	r2, r3, #0
	bl	read
	add	r3, r0, #0
	cmp	r3, #0
	blt	.L5	@cond_branch
	mov	r1, sp
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r2, #85
	eor	r0, r0, r2
	strb	r0, [r1]
	sub	r0, r3, #1
	mov	r5, sp
	add	r1, r5, r0
	ldrb	r0, [r1]
	eor	r0, r0, r2
	strb	r0, [r1]
	add	r0, r4, #0
	mov	r1, sp
	add	r2, r3, #0
	bl	write
	b	.L6
.L8:
	.align	2, 0
.L7:
	.word	-1193048
	.word	1193046
.L5:
	add	r0, r3, #0
.L6:
	ldr	r3, .L9
	add	sp, sp, r3
	pop	{r4, r5, pc}
.L10:
	.align	2, 0
.L9:
	.word	1193048
.Lfe3:
	.size	 test,.Lfe3-test
