@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test_0
	.type	 test_0,function
	.thumb_func
test_0:
	ldr	r2, [r1, #4]		@ created by thumb_load_double_from_address
	ldr	r1, [r1]		@ created by thumb_load_double_from_address
	str	r1, [r0]
	str	r2, [r0, #4]
	bx	lr
.Lfe1:
	.size	 test_0,.Lfe1-test_0
	.align	2, 0
	.globl	test_1
	.type	 test_1,function
	.thumb_func
test_1:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	pop	{r4, pc}
.Lfe2:
	.size	 test_1,.Lfe2-test_1
	.align	2, 0
	.globl	test_2
	.type	 test_2,function
	.thumb_func
test_2:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	pop	{r4, pc}
.Lfe3:
	.size	 test_2,.Lfe3-test_2
	.align	2, 0
	.globl	test_3
	.type	 test_3,function
	.thumb_func
test_3:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	pop	{r4, pc}
.Lfe4:
	.size	 test_3,.Lfe4-test_3
	.align	2, 0
	.globl	test_4
	.type	 test_4,function
	.thumb_func
test_4:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	pop	{r4, pc}
.Lfe5:
	.size	 test_4,.Lfe5-test_4
	.align	2, 0
	.globl	test_5
	.type	 test_5,function
	.thumb_func
test_5:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	ldr	r1, [r1]
	str	r1, [r0]
	pop	{r4, pc}
.Lfe6:
	.size	 test_5,.Lfe6-test_5
	.align	2, 0
	.globl	test_6
	.type	 test_6,function
	.thumb_func
test_6:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	ldr	r1, [r1]
	str	r1, [r0]
	pop	{r4, pc}
.Lfe7:
	.size	 test_6,.Lfe7-test_6
	.align	2, 0
	.globl	test_7
	.type	 test_7,function
	.thumb_func
test_7:
	push	{r4, lr}
	ldmia	r1!, {r2, r3, r4}
	stmia	r0!, {r2, r3, r4}
	ldr	r1, [r1]
	str	r1, [r0]
	ldr	r1, .L10
	ldr	r0, .L10+4
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr	r0, [r0]
	str	r0, [r1]
	pop	{r4, pc}
.L11:
	.align	2, 0
.L10:
	.word	d7
	.word	s7
.Lfe8:
	.size	 test_7,.Lfe8-test_7
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	bx	lr
.Lfe9:
	.size	 test,.Lfe9-test
	.comm	s7, 16	@ 16
	.comm	d7, 16	@ 16
