@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	bar
	.type	 bar,function
	.thumb_func
bar:
	bx	lr
.Lfe1:
	.size	 bar,.Lfe1-bar
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	bl	bar
	ldr	r1, .L4
	mov	r0, #4
	str	r0, [r1]
	pop	{pc}
.L5:
	.align	2, 0
.L4:
	.word	foo
.Lfe2:
	.size	 test,.Lfe2-test
	.comm	foo, 4	@ 4
