@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	r4, r0, #0
	ldr	r1, .L5
	bl	__eqsf2
	ldr	r1, .L5+4
	cmp	r0, #0
	bne	.L3	@cond_branch
	add	r1, r4, #0
.L3:
	add	r0, r1, #0
	pop	{r4, pc}
.L6:
	.align	2, 0
.L5:
	.word 0x0	@ float 0.00000000000000000000e0
	.word 0x41700000	@ float 1.50000000000000000000e1
.Lfe1:
	.size	 test,.Lfe1-test
