.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching test, 0x58

glabel test # 0
    /* 000100 00000100 3C020000 */  lui         $v0, %hi(global)
    /* 000104 00000104 00857026 */  xor         $t6, $a0, $a1
    /* 000108 00000108 24420000 */  addiu       $v0, $v0, %lo(global)
    /* 00010C 0000010C 2DCE0001 */  sltiu       $t6, $t6, 0x1
    /* 000110 00000110 00867826 */  xor         $t7, $a0, $a2
    /* 000114 00000114 AC4E0000 */  sw          $t6, 0x0($v0)
    /* 000118 00000118 000F782B */  sltu        $t7, $zero, $t7
    /* 00011C 0000011C AC4F0000 */  sw          $t7, 0x0($v0)
    /* 000120 00000120 0085C02A */  slt         $t8, $a0, $a1
    /* 000124 00000124 00A4C82A */  slt         $t9, $a1, $a0
    /* 000128 00000128 AC580000 */  sw          $t8, 0x0($v0)
    /* 00012C 0000012C 3B390001 */  xori        $t9, $t9, 0x1
    /* 000130 00000130 AC590000 */  sw          $t9, 0x0($v0)
    /* 000134 00000134 2C880001 */  sltiu       $t0, $a0, 0x1
    /* 000138 00000138 AC480000 */  sw          $t0, 0x0($v0)
    /* 00013C 0000013C 0005482B */  sltu        $t1, $zero, $a1
    /* 000140 00000140 AC490000 */  sw          $t1, 0x0($v0)
    /* 000144 00000144 0005502A */  slt         $t2, $zero, $a1
    /* 000148 00000148 AC4A0000 */  sw          $t2, 0x0($v0)
    /* 00014C 0000014C 28AB0001 */  slti        $t3, $a1, 0x1
    /* 000150 00000150 03E00008 */  jr          $ra
    /* 000154 00000154 AC4B0000 */   sw         $t3, 0x0($v0)
endlabel test
    /* 000158 00000158 00000000 */  nop
    /* 00015C 0000015C 00000000 */  nop
.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching global, 0x4

dlabel global
    /* 00000160 */ .space 0x04

nonmatching B_00000164, 0xC

/* Automatically generated and unreferenced pad */
dlabel B_00000164
    /* 00000164 */ .space 0x0C
