@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r0, .L3
	ldr	r2, .L3+4
	str	r2, [r0]
	ldr	r1, .L3+8
	str	r1, [r0]
	ldr	r0, .L3+12
	str	r2, [r0]
	str	r1, [r0]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	glob
	.word	foo
	.word	bar
	.word	glob2
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	mov	r0, #1
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
	.align	2, 0
	.globl	bar
	.type	 bar,function
	.thumb_func
bar:
	mov	r0, #2
	bx	lr
.Lfe3:
	.size	 bar,.Lfe3-bar
	.comm	glob, 4	@ 4
	.comm	glob2, 4	@ 4
