@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	add	r5, r0, #0
	add	r4, r1, #0
	add	r6, r3, #0
	mov	r1, #0
	b	.L34
.L5:
	add	r1, r1, #1
.L34:
	cmp	r5, #0
	beq	.L31	@cond_branch
	cmp	r4, #0
	bne	.L5	@cond_branch
	cmp	r2, #0
	bne	.L5	@cond_branch
	cmp	r5, #0
	bne	.L10	@cond_branch
.L31:
	cmp	r4, #0
	beq	.L13	@cond_branch
	cmp	r2, #0
	beq	.L13	@cond_branch
.L10:
	add	r1, r1, #1
	cmp	r5, #0
	bne	.L10	@cond_branch
	cmp	r4, #0
	beq	.L13	@cond_branch
	cmp	r2, #0
	bne	.L10	@cond_branch
	b	.L13
.L33:
	cmp	r6, #0
	bne	.L14	@cond_branch
.L22:
	add	r1, r1, #1
.L13:
	cmp	r5, #0
	beq	.L14	@cond_branch
	add	r1, r1, #1
	cmp	r4, #0
	beq	.L16	@cond_branch
	cmp	r2, #0
	bne	.L13	@cond_branch
	cmp	r6, #0
	bne	.L13	@cond_branch
.L16:
	add	r1, r1, #1
	cmp	r4, #0
	bne	.L13	@cond_branch
	cmp	r2, #0
	beq	.L18	@cond_branch
	cmp	r6, #0
	bne	.L13	@cond_branch
.L18:
	add	r1, r1, #2
	cmp	r2, #0
	beq	.L22	@cond_branch
	b	.L33
.L14:
	mov	r3, #0
	b	.L35
.L28:
	add	r1, r1, #1
	add	r0, r2, r6
	add	r3, r3, r0
	cmp	r3, #9
	bgt	.L26	@cond_branch
.L35:
	cmp	r5, #0
	bne	.L28	@cond_branch
	cmp	r4, #0
	bne	.L28	@cond_branch
.L26:
	add	r0, r1, #0
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 test,.Lfe1-test
