@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test_s8
	.type	 test_s8,function
	.thumb_func
test_s8:
	push	{lr}
	add	sp, sp, #-4
	mov	r1, sp
	strb	r0, [r1]
	mov	r0, sp
	ldrb	r0, [r0]
	lsr	r0, r0, #1
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #3
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #5
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #7
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #10
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #100
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #255
	bl	__udivsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r1, [r0]
	mov	r0, #1
	and	r0, r0, r1
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #3
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #5
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #7
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #10
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #100
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	mov	r0, sp
	ldrb	r0, [r0]
	mov	r1, #255
	bl	__umodsi3
	lsl	r0, r0, #24
	lsr	r0, r0, #24
	bl	foo
	add	sp, sp, #4
	pop	{pc}
.Lfe1:
	.size	 test_s8,.Lfe1-test_s8
	.align	2, 0
	.globl	test_s16
	.type	 test_s16,function
	.thumb_func
test_s16:
	push	{r4, r5, lr}
	add	sp, sp, #-4
	mov	r1, sp
	strh	r0, [r1]
	mov	r0, sp
	ldrh	r1, [r0]
	lsl	r1, r1, #16
	asr	r0, r1, #16
	lsr	r1, r1, #31
	add	r0, r0, r1
	asr	r0, r0, #1
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #3
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #5
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #7
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #10
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #100
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #255
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r5, #180
	lsl	r5, r5, #1
	add	r1, r5, #0
	bl	__divsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	ldr	r4, .L4
	add	r1, r4, #0
	bl	__divsi3
	bl	foo
	mov	r0, sp
	ldrh	r1, [r0]
	lsl	r1, r1, #16
	asr	r0, r1, #16
	lsr	r1, r1, #31
	add	r1, r0, r1
	asr	r1, r1, #1
	lsl	r1, r1, #1
	sub	r0, r0, r1
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #3
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #5
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #7
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #10
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #100
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	mov	r1, #255
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	add	r1, r5, #0
	bl	__modsi3
	lsl	r0, r0, #16
	asr	r0, r0, #16
	bl	foo
	mov	r0, sp
	ldrh	r0, [r0]
	lsl	r0, r0, #16
	asr	r0, r0, #16
	add	r1, r4, #0
	bl	__modsi3
	bl	foo
	add	sp, sp, #4
	pop	{r4, r5, pc}
.L5:
	.align	2, 0
.L4:
	.word	65534
.Lfe2:
	.size	 test_s16,.Lfe2-test_s16
	.align	2, 0
	.globl	test_s32_div
	.type	 test_s32_div,function
	.thumb_func
test_s32_div:
	push	{lr}
	add	sp, sp, #-4
	str	r0, [sp]
	ldr	r0, [sp]
	bl	foo
	ldr	r0, [sp]
	lsr	r1, r0, #31
	add	r0, r0, r1
	asr	r0, r0, #1
	bl	foo
	ldr	r0, [sp]
	mov	r1, #3
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L7	@cond_branch
	add	r0, r0, #3
.L7:
	asr	r0, r0, #2
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #6
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #7
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L8	@cond_branch
	add	r0, r0, #7
.L8:
	asr	r0, r0, #3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #9
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #11
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #12
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #13
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #14
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #15
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L9	@cond_branch
	add	r0, r0, #15
.L9:
	asr	r0, r0, #4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #17
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #18
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #19
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #20
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #21
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #22
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #23
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #24
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #25
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #26
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #27
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #28
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #29
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #30
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #31
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L10	@cond_branch
	add	r0, r0, #31
.L10:
	asr	r0, r0, #5
	bl	foo
	ldr	r0, [sp]
	mov	r1, #33
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #100
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #255
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #180
	lsl	r1, r1, #1
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #250
	lsl	r1, r1, #2
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+4
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+8
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+12
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+16
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+20
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+24
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L11	@cond_branch
	ldr	r1, .L13+24
	add	r0, r0, r1
.L11:
	asr	r0, r0, #30
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+28
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+32
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+36
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+40
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #31
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+44
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L13+48
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	neg	r1, r1
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #7
	neg	r1, r1
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	neg	r1, r1
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	cmp	r0, #0
	bge	.L12	@cond_branch
	add	r0, r0, #3
.L12:
	asr	r0, r0, #2
	neg	r0, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #3
	neg	r1, r1
	bl	__divsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r1, r0, #31
	add	r0, r0, r1
	asr	r0, r0, #1
	neg	r0, r0
	bl	foo
	ldr	r0, [sp]
	neg	r0, r0
	bl	foo
	add	sp, sp, #4
	pop	{pc}
.L14:
	.align	2, 0
.L13:
	.word	10000
	.word	100000
	.word	1000000
	.word	10000000
	.word	100000000
	.word	1073741822
	.word	1073741823
	.word	1073741825
	.word	2147483645
	.word	2147483646
	.word	2147483647
	.word	-2147483647
	.word	-2147483646
.Lfe3:
	.size	 test_s32_div,.Lfe3-test_s32_div
	.align	2, 0
	.globl	test_s32_mod
	.type	 test_s32_mod,function
	.thumb_func
test_s32_mod:
	push	{r4, r5, lr}
	add	sp, sp, #-4
	str	r0, [sp]
	ldr	r0, [sp]
	mov	r0, #0
	bl	foo
	ldr	r0, [sp]
	lsr	r1, r0, #31
	add	r1, r0, r1
	asr	r1, r1, #1
	lsl	r1, r1, #1
	sub	r0, r0, r1
	bl	foo
	ldr	r0, [sp]
	mov	r1, #3
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L16	@cond_branch
	add	r0, r1, #3
.L16:
	asr	r0, r0, #2
	lsl	r0, r0, #2
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #6
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #7
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L17	@cond_branch
	add	r0, r1, #7
.L17:
	asr	r0, r0, #3
	lsl	r0, r0, #3
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #9
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #11
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #12
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #13
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #14
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #15
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L18	@cond_branch
	add	r0, r0, #15
.L18:
	asr	r0, r0, #4
	lsl	r0, r0, #4
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #17
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #18
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #19
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #20
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #21
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #22
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #23
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #24
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #25
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #26
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #27
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #28
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #29
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #30
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #31
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L19	@cond_branch
	add	r0, r0, #31
.L19:
	asr	r0, r0, #5
	lsl	r0, r0, #5
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #33
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #100
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #255
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #180
	lsl	r1, r1, #1
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #250
	lsl	r1, r1, #2
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+4
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+8
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+12
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+16
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+20
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+24
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L20	@cond_branch
	ldr	r2, .L22+24
	add	r0, r1, r2
.L20:
	asr	r0, r0, #30
	lsl	r0, r0, #30
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+28
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L22+32
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r5, .L22+36
	add	r1, r5, #0
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r4, .L22+40
	add	r1, r4, #0
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	add	r1, r4, #0
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	add	r1, r5, #0
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #7
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	bl	__modsi3
	bl	foo
	ldr	r1, [sp]
	add	r0, r1, #0
	cmp	r1, #0
	bge	.L21	@cond_branch
	add	r0, r1, #3
.L21:
	asr	r0, r0, #2
	lsl	r0, r0, #2
	sub	r0, r1, r0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #3
	bl	__modsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r1, r0, #31
	add	r1, r0, r1
	asr	r1, r1, #1
	lsl	r1, r1, #1
	sub	r0, r0, r1
	bl	foo
	ldr	r0, [sp]
	mov	r0, #0
	bl	foo
	add	sp, sp, #4
	pop	{r4, r5, pc}
.L23:
	.align	2, 0
.L22:
	.word	10000
	.word	100000
	.word	1000000
	.word	10000000
	.word	100000000
	.word	1073741822
	.word	1073741823
	.word	1073741825
	.word	2147483645
	.word	2147483646
	.word	2147483647
.Lfe4:
	.size	 test_s32_mod,.Lfe4-test_s32_mod
	.align	2, 0
	.globl	test_u32_div
	.type	 test_u32_div,function
	.thumb_func
test_u32_div:
	push	{lr}
	add	sp, sp, #-4
	str	r0, [sp]
	ldr	r0, [sp]
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #1
	bl	foo
	ldr	r0, [sp]
	mov	r1, #3
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #2
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #6
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #7
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #9
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #11
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #12
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #13
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #14
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #15
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #17
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #18
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #19
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #20
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #21
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #22
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #23
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #24
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #25
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #26
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #27
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #28
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #29
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #30
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #31
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #5
	bl	foo
	ldr	r0, [sp]
	mov	r1, #33
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #100
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #255
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #180
	lsl	r1, r1, #1
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #250
	lsl	r1, r1, #2
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+4
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+8
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+12
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+16
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #30
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+20
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+24
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+28
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	lsr	r0, r0, #31
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L25+32
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #2
	neg	r1, r1
	bl	__udivsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #1
	neg	r1, r1
	bl	__udivsi3
	bl	foo
	add	sp, sp, #4
	pop	{pc}
.L26:
	.align	2, 0
.L25:
	.word	10000
	.word	100000
	.word	1000000
	.word	10000000
	.word	100000000
	.word	1073741825
	.word	2147483646
	.word	2147483647
	.word	-2147483647
.Lfe5:
	.size	 test_u32_div,.Lfe5-test_u32_div
	.align	2, 0
	.globl	test_u32_mod
	.type	 test_u32_mod,function
	.thumb_func
test_u32_mod:
	push	{r4, lr}
	add	sp, sp, #-4
	str	r0, [sp]
	ldr	r0, [sp]
	mov	r0, #0
	bl	foo
	ldr	r0, [sp]
	mov	r1, #1
	and	r0, r0, r1
	bl	foo
	ldr	r0, [sp]
	mov	r4, #3
	mov	r1, #3
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #5
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #6
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r4, #7
	mov	r1, #7
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #9
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #10
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #11
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #12
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #13
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #14
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r4, #15
	mov	r1, #15
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #17
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #18
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #19
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #20
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #21
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #22
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #23
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #24
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #25
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #26
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #27
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #28
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #29
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #30
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r4, #31
	mov	r1, #31
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	mov	r1, #33
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #100
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #255
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #180
	lsl	r1, r1, #1
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #250
	lsl	r1, r1, #2
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+4
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+8
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+12
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+16
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+20
	and	r0, r0, r1
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+24
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+28
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	ldr	r4, .L28+32
	add	r1, r4, #0
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	and	r0, r0, r4
	bl	foo
	ldr	r0, [sp]
	ldr	r1, .L28+36
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #2
	neg	r1, r1
	bl	__umodsi3
	bl	foo
	ldr	r0, [sp]
	mov	r1, #1
	neg	r1, r1
	bl	__umodsi3
	bl	foo
	add	sp, sp, #4
	pop	{r4, pc}
.L29:
	.align	2, 0
.L28:
	.word	10000
	.word	100000
	.word	1000000
	.word	10000000
	.word	100000000
	.word	1073741823
	.word	1073741825
	.word	2147483646
	.word	2147483647
	.word	-2147483647
.Lfe6:
	.size	 test_u32_mod,.Lfe6-test_u32_mod
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	r4, r0, #0
	lsl	r0, r4, #24
	lsr	r0, r0, #24
	bl	test_s8
	lsl	r0, r4, #16
	asr	r0, r0, #16
	bl	test_s16
	add	r0, r4, #0
	bl	test_s32_div
	add	r0, r4, #0
	bl	test_s32_mod
	add	r0, r4, #0
	bl	test_u32_div
	add	r0, r4, #0
	bl	test_u32_mod
	pop	{r4, pc}
.Lfe7:
	.size	 test,.Lfe7-test
