@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	r4, r0, #0
	cmp	r4, #7
	bne	.L3	@cond_branch
	mov	r0, #1
	bl	foo
	mov	r0, #3
	bl	foo
	b	.L2
.L3:
	mov	r0, #4
	bl	foo
	cmp	r4, #9
	bne	.L6	@cond_branch
	mov	r0, #5
	bl	foo
.L6:
	mov	r0, #6
	bl	foo
.L2:
	pop	{r4, pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
