@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r2, r0, #0
	cmp	r2, #50
	beq	.L11	@cond_branch
	cmp	r2, #50
	bgt	.L22	@cond_branch
	cmp	r2, #2
	beq	.L5	@cond_branch
	cmp	r2, #2
	bgt	.L23	@cond_branch
	mov	r0, #50
	neg	r0, r0
	cmp	r2, r0
	beq	.L10	@cond_branch
	cmp	r2, #1
	beq	.L4	@cond_branch
	b	.L20
.L23:
	cmp	r2, #3
	beq	.L8	@cond_branch
	cmp	r2, #7
	bgt	.L20	@cond_branch
	cmp	r2, #6
	blt	.L20	@cond_branch
	lsl	r2, r2, #1
	b	.L14
.L22:
	cmp	r2, #106
	bgt	.L24	@cond_branch
	cmp	r2, #103
	bge	.L19	@cond_branch
	cmp	r2, #101
	beq	.L8	@cond_branch
	cmp	r2, #102
	beq	.L14	@cond_branch
	b	.L20
.L24:
	cmp	r2, #107
	beq	.L9	@cond_branch
	cmp	r2, #200
	beq	.L8	@cond_branch
	b	.L20
.L4:
	mov	r0, #1
	b	.L25
.L5:
	mov	r2, #1
.L8:
	add	r0, r2, #1
	eor	r0, r0, r2
	b	.L25
.L9:
	mov	r2, #108
	b	.L26
.L10:
	sub	r2, r2, #1
	b	.L26
.L11:
	mov	r2, #51
	b	.L26
.L14:
	ldr	r0, .L27
	ldr	r1, [r0]
	cmp	r1, #0
	bne	.L3	@cond_branch
.L19:
	sub	r2, r2, #1
.L20:
	lsr	r0, r2, #31
	add	r0, r2, r0
	asr	r2, r0, #1
.L26:
	ldr	r0, .L27
.L3:
	str	r2, [r0]
	mov	r0, #2
.L25:
	pop	{pc}
.L28:
	.align	2, 0
.L27:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
