@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	sub	sp, sp, #4
	push	{r4, r5, r6, r7, lr}
	add	r7, r1, #0
	add	r6, r0, #0
	add	r0, r2, #0
	str	r3, [sp, #20]
	bl	__floatsidf
	add	r3, r1, #0
	add	r2, r0, #0
	add	r1, r7, #0
	add	r0, r6, #0
	bl	__muldf3
	add	r5, r1, #0
	add	r4, r0, #0
	add	r1, r7, #0
	add	r0, r6, #0
	ldr	r2, [sp, #20]		@ created by thumb_load_double_from_address
	ldr	r3, [sp, #24]		@ created by thumb_load_double_from_address
	bl	__divdf3
	add	r3, r1, #0
	add	r2, r0, #0
	add	r1, r5, #0
	add	r0, r4, #0
	bl	__adddf3
	ldr	r3, .L6+4		@ created by thumb_load_double_from_address
	ldr	r2, .L6		@ created by thumb_load_double_from_address
	bl	__subdf3
	add	r5, r1, #0
	add	r4, r0, #0
	ldr	r2, [sp, #20]		@ created by thumb_load_double_from_address
	ldr	r3, [sp, #24]		@ created by thumb_load_double_from_address
	bl	__ltdf2
	cmp	r0, #0
	blt	.L4	@cond_branch
	add	r1, r5, #0
	add	r0, r4, #0
	ldr	r2, [sp, #20]		@ created by thumb_load_double_from_address
	ldr	r3, [sp, #24]		@ created by thumb_load_double_from_address
	bl	__eqdf2
	cmp	r0, #0
	beq	.L4	@cond_branch
	ldr	r2, .L6+8		@ created by thumb_load_double_from_address
	ldr	r3, .L6+12		@ created by thumb_load_double_from_address
	add	r1, r5, #0
	add	r0, r4, #0
	bl	__gtdf2
	cmp	r0, #0
	ble	.L3	@cond_branch
.L4:
	ldr	r1, .L6+16		@ created by thumb_load_double_from_address
	ldr	r2, .L6+20		@ created by thumb_load_double_from_address
	b	.L5
.L7:
	.align	2, 0
.L6:
	.long 0x401c0000, 0x0	@ double 7.00000000000000000000e0
	.long 0x40220000, 0x0	@ double 9.00000000000000000000e0
	.long 0x40140000, 0x0	@ double 5.00000000000000000000e0
.L3:
	ldr	r2, .L8+4		@ created by thumb_load_double_from_address
	ldr	r1, .L8		@ created by thumb_load_double_from_address
.L5:
	ldr	r0, .L8+8
	str	r1, [r0]
	str	r2, [r0, #4]
	add	r0, r1, #0
	add	r1, r2, #0
	pop	{r4, r5, r6, r7}
	pop	{r3}
	add	sp, sp, #4
	bx	r3
.L9:
	.align	2, 0
.L8:
	.long 0x40180000, 0x0	@ double 6.00000000000000000000e0
	.word	global
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	global, 8	@ 8
