@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	add	r4, r0, #0
	ldr	r1, .L5
	bl	__gesf2
	cmp	r0, #0
	bge	.L3	@cond_branch
	add	r0, r4, #0
	bl	__negsf2
	add	r4, r0, #0
.L3:
	add	r0, r4, #0
	bl	sqrtf
	bl	__extendsfdf2
	add	r5, r1, #0
	add	r4, r0, #0
	ldr	r2, .L5+4		@ created by thumb_load_double_from_address
	ldr	r3, .L5+8		@ created by thumb_load_double_from_address
	bl	__gedf2
	cmp	r0, #0
	bge	.L4	@cond_branch
	add	r1, r5, #0
	add	r0, r4, #0
	bl	__negdf2
	add	r5, r1, #0
	add	r4, r0, #0
.L4:
	add	r1, r5, #0
	add	r0, r4, #0
	bl	sqrt
	bl	__truncdfsf2
	pop	{r4, r5, pc}
.L6:
	.align	2, 0
.L5:
	.word 0x0	@ float 0.00000000000000000000e0
	.long 0x0, 0x0	@ double 0.00000000000000000000e0
.Lfe1:
	.size	 test,.Lfe1-test
