@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, [r1]
	cmp	r0, #1
	beq	.L5	@cond_branch
	cmp	r0, #1
	bcc	.L6	@cond_branch
	cmp	r0, #2
	beq	.L6	@cond_branch
	ldr	r0, .L12
	b	.L9
.L13:
	.align	2, 0
.L12:
	.word 0x0	@ float 0.00000000000000000000e0
.L5:
.L6:
	ldr	r0, [r1, #4]
	ldr	r1, [r1, #12]
	bl	__addsf3
.L9:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
