@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	mov	r0, #1
	bl	foo
	lsl	r0, r0, #16
	lsr	r0, r0, #16
	cmp	r0, #0
	bne	.L6	@cond_branch
	ldr	r0, .L9
	ldr	r0, [r0]
	cmp	r0, #123
	bne	.L4	@cond_branch
	mov	r0, #3
	b	.L8
.L10:
	.align	2, 0
.L9:
	.word	glob
.L4:
	mov	r0, #2
.L8:
	bl	foo
	lsl	r0, r0, #16
	lsr	r0, r0, #16
.L6:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	mov	r0, #1
	bx	lr
.Lfe2:
	.size	 foo,.Lfe2-foo
	.comm	glob, 4	@ 4
