@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	add	r0, r0, #1
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	add	r5, r1, #0
	add	r7, r2, #0
	mov	r9, r3
	add	r4, r0, r5
	add	r6, r5, r7
	add	r1, r7, #0
	add	r1, r1, r9
	mov	r8, r1
	cmp	r4, #0
	beq	.L4	@cond_branch
	cmp	r6, #0
	beq	.L4	@cond_branch
	cmp	r1, #0
	beq	.L4	@cond_branch
	add	r0, r4, r0
	bl	foo
	add	r4, r0, #0
	cmp	r4, #10
	ble	.L4	@cond_branch
	add	r0, r4, r5
	bl	foo
	add	r4, r0, #0
	add	r0, r6, r7
	bl	foo
	add	r6, r0, #0
	mov	r0, r8
	add	r0, r0, r9
	bl	foo
	cmp	r4, #0
	beq	.L4	@cond_branch
	cmp	r6, #0
	beq	.L4	@cond_branch
	cmp	r0, #0
	beq	.L4	@cond_branch
	mov	r0, #1
	b	.L7
.L4:
	mov	r0, #0
.L7:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7, pc}
.Lfe2:
	.size	 test,.Lfe2-test
