@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.section .rodata
	.align	2, 0
.LC0:
	.ascii	"abcdef\000"
	.align	2, 0
.LC6:
	.ascii	"ghi\000"
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	add	sp, sp, #-8
	ldr	r1, .L4
	mov	r0, sp
	mov	r2, #7
	bl	memcpy
	mov	r0, sp
	bl	foo
	ldr	r1, .L4+4
	ldr	r0, .L4+8
	ldr	r0, [r0, #4]
	str	r0, [r1, #4]
	ldr	r0, .L4+12
	ldmia	r1!, {r2, r3}
	stmia	r0!, {r2, r3}
	ldr	r0, .L4+16
	ldr	r1, .L4+20
	mov	r2, #4
	bl	memcpy
	add	sp, sp, #8
	pop	{pc}
.L5:
	.align	2, 0
.L4:
	.word	.LC0
	.word	a1
	.word	a2
	.word	a3
	.word	buf
	.word	.LC6
.Lfe2:
	.size	 test,.Lfe2-test
	.comm	a1, 8	@ 8
	.comm	a2, 8	@ 8
	.comm	a3, 8	@ 8
	.comm	buf, 100	@ 100
