@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	array
	.section .rodata
	.align	2, 0
	.type	 array,object
	.size	 array,16
array:
	.word	3
	.word	2
	.word	2
	.word	0
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	cmp	r0, #2
	beq	.L5	@cond_branch
	cmp	r0, #2
	bhi	.L9	@cond_branch
	cmp	r0, #0
	beq	.L4	@cond_branch
	b	.L3
.L9:
	cmp	r0, #3
	beq	.L6	@cond_branch
	b	.L3
.L4:
	ldr	r0, .L11
	ldr	r0, [r0]
	b	.L10
.L12:
	.align	2, 0
.L11:
	.word	array
.L5:
	ldr	r0, .L13
	ldr	r0, [r0, #4]
	b	.L10
.L14:
	.align	2, 0
.L13:
	.word	array
.L6:
	ldr	r0, .L15
	ldr	r0, [r0, #8]
	b	.L10
.L16:
	.align	2, 0
.L15:
	.word	array
.L3:
	mov	r0, #0
.L10:
	pop	{pc}
.Lfe1:
	.size	 test,.Lfe1-test
