.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching test, 0x78

glabel test # 0
    /* 0000F0 000000F0 27BDFFF8 */  addiu       $sp, $sp, -0x8
    /* 0000F4 000000F4 00802825 */  move        $a1, $a0
    /* 0000F8 000000F8 10A00009 */  beqz        $a1, .L00000120
    /* 0000FC 000000FC 00000000 */   nop
    /* 000100 00000100 24010002 */  addiu       $at, $zero, 0x2
    /* 000104 00000104 10A1000A */  beq         $a1, $at, .L00000130
    /* 000108 00000108 00000000 */   nop
    /* 00010C 0000010C 24010003 */  addiu       $at, $zero, 0x3
    /* 000110 00000110 10A1000B */  beq         $a1, $at, .L00000140
    /* 000114 00000114 00000000 */   nop
    /* 000118 00000118 1000000D */  b           .L00000150
    /* 00011C 0000011C 00000000 */   nop
  .L00000120:
    /* 000120 00000120 3C0E0000 */  lui         $t6, %hi(array)
    /* 000124 00000124 25CE0000 */  addiu       $t6, $t6, %lo(array)
    /* 000128 00000128 1000000D */  b           .L00000160
    /* 00012C 0000012C 8DC20000 */   lw         $v0, 0x0($t6)
  .L00000130:
    /* 000130 00000130 3C0F0000 */  lui         $t7, %hi(array)
    /* 000134 00000134 25EF0000 */  addiu       $t7, $t7, %lo(array)
    /* 000138 00000138 10000009 */  b           .L00000160
    /* 00013C 0000013C 8DE20004 */   lw         $v0, 0x4($t7)
  .L00000140:
    /* 000140 00000140 3C180000 */  lui         $t8, %hi(array)
    /* 000144 00000144 27180000 */  addiu       $t8, $t8, %lo(array)
    /* 000148 00000148 10000005 */  b           .L00000160
    /* 00014C 0000014C 8F020008 */   lw         $v0, 0x8($t8)
  .L00000150:
    /* 000150 00000150 10000003 */  b           .L00000160
    /* 000154 00000154 00001025 */   move       $v0, $zero
    /* 000158 00000158 10000001 */  b           .L00000160
    /* 00015C 0000015C 00000000 */   nop
  .L00000160:
    /* 000160 00000160 03E00008 */  jr          $ra
    /* 000164 00000164 27BD0008 */   addiu      $sp, $sp, 0x8
endlabel test
    /* 000168 00000168 00000000 */  nop
    /* 00016C 0000016C 00000000 */  nop
.include "macro.inc"

.section .rodata

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching array

dlabel array
    /* 000170 00000170 00000003 */ .word 0x00000003
    /* 000174 00000174 00000002 */ .word 0x00000002
    /* 000178 00000178 00000002 */ .word 0x00000002
    /* 00017C 0000017C 00000000 */ .word 0x00000000
enddlabel array
