.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching test, 0x48

glabel test # 0
    /* 0000F0 000000F0 10800009 */  beqz        $a0, .L00000118
    /* 0000F4 000000F4 3C020000 */   lui        $v0, %hi(array)
    /* 0000F8 000000F8 24010002 */  addiu       $at, $zero, 0x2
    /* 0000FC 000000FC 10810008 */  beq         $a0, $at, .L00000120
    /* 000100 00000100 3C020000 */   lui        $v0, %hi(array + 0x4)
    /* 000104 00000104 24010003 */  addiu       $at, $zero, 0x3
    /* 000108 00000108 10810007 */  beq         $a0, $at, .L00000128
    /* 00010C 0000010C 3C020000 */   lui        $v0, %hi(array + 0x8)
    /* 000110 00000110 10000007 */  b           .L00000130
    /* 000114 00000114 00001025 */   move       $v0, $zero
  .L00000118:
    /* 000118 00000118 03E00008 */  jr          $ra
    /* 00011C 0000011C 8C420000 */   lw         $v0, %lo(array)($v0)
  .L00000120:
    /* 000120 00000120 03E00008 */  jr          $ra
    /* 000124 00000124 8C420004 */   lw         $v0, %lo(array + 0x4)($v0)
  .L00000128:
    /* 000128 00000128 03E00008 */  jr          $ra
    /* 00012C 0000012C 8C420008 */   lw         $v0, %lo(array + 0x8)($v0)
  .L00000130:
    /* 000130 00000130 03E00008 */  jr          $ra
    /* 000134 00000134 00000000 */   nop
endlabel test
    /* 000138 00000138 00000000 */  nop
    /* 00013C 0000013C 00000000 */  nop
.include "macro.inc"

.section .rodata

.align 4

/* Generated by spimdisasm 1.41.0 */

nonmatching array

dlabel array
    /* 000140 00000140 00000003 */ .word 0x00000003
    /* 000144 00000144 00000002 */ .word 0x00000002
    /* 000148 00000148 00000002 */ .word 0x00000002
    /* 00014C 0000014C 00000000 */ .word 0x00000000
enddlabel array
