@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foo
	.type	 foo,function
	.thumb_func
foo:
	ldr	r1, [r1]
	add	r0, r0, r1
	bx	lr
.Lfe1:
	.size	 foo,.Lfe1-foo
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-4
	str	r0, [sp]
	add	r5, r1, #0
	mov	r1, sp
	bl	foo
	add	r4, r0, #0
	ldr	r0, [sp]
	add	r1, r5, #0
	bl	foo
	add	r6, r0, #0
	ldr	r0, [r5]
	add	r1, r5, #0
	bl	foo
	add	r4, r4, r6
	add	r4, r4, r0
	add	r0, r4, #0
	add	sp, sp, #4
	pop	{r4, r5, r6, pc}
.Lfe2:
	.size	 test,.Lfe2-test
