@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	ldr	r3, .L3
	lsl	r1, r0, #24
	lsr	r1, r1, #24
	str	r1, [r3]
	lsl	r2, r0, #1
	lsl	r1, r0, #25
	lsr	r1, r1, #24
	str	r1, [r3]
	add	r2, r2, r0
	lsl	r1, r2, #24
	lsr	r1, r1, #24
	str	r1, [r3]
	lsl	r1, r0, #16
	asr	r1, r1, #16
	str	r1, [r3]
	lsl	r0, r0, #17
	asr	r0, r0, #16
	str	r0, [r3]
	lsl	r2, r2, #16
	asr	r2, r2, #16
	str	r2, [r3]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
