@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, r5, lr}
	add	r4, r0, #0
	ldr	r1, .L3
	bl	__mulsf3
	asr	r4, r4, #1
	ldr	r5, .L3+4
	sub	r5, r5, r4
	add	r1, r5, #0
	bl	__mulsf3
	add	r1, r5, #0
	bl	__mulsf3
	add	r1, r0, #0
	ldr	r0, .L3+8
	bl	__subsf3
	add	r1, r0, #0
	add	r0, r5, #0
	bl	__mulsf3
	pop	{r4, r5, pc}
.L4:
	.align	2, 0
.L3:
	.word 0x3f000000	@ float 5.00000000000000000000e-1
	.word	1597463007
	.word 0x3fc00000	@ float 1.50000000000000000000e0
.Lfe1:
	.size	 test,.Lfe1-test
