@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{lr}
	cmp	r0, #5
	bne	.L4	@cond_branch
	ldr	r1, .L7
.L5:
	str	r0, [r1]
	add	r0, r0, #1
	str	r0, [r1]
	add	r0, r0, #1
	str	r0, [r1]
	add	r0, r0, #1
	str	r0, [r1]
	add	r2, r0, #0
	add	r0, r2, #1
	str	r0, [r1]
	str	r0, [r1]
	add	r0, r0, #1
	str	r0, [r1]
	add	r0, r0, #1
	str	r2, [r1]
	cmp	r0, #5
	beq	.L5	@cond_branch
.L4:
	add	r0, r2, #0
	pop	{pc}
.L8:
	.align	2, 0
.L7:
	.word	glob
.Lfe1:
	.size	 test,.Lfe1-test
	.comm	glob, 4	@ 4
