@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r7, lr}
	add	sp, sp, #-12
	mov	r7, sp
	str	r0, [r7]
	str	r1, [r7, #4]
	mov	r0, #0
	str	r0, [r7, #8]
.L3:
	ldr	r0, [r7, #8]
	ldr	r1, [r7, #4]
	cmp	r0, r1
	blt	.L6	@cond_branch
	b	.L4
.L6:
	ldr	r0, [r7]
	ldr	r1, [r7, #8]
	add	r0, r0, r1
	mov	r1, #0
	strb	r1, [r0]
.L5:
	ldr	r0, [r7, #8]
	add	r1, r0, #1
	str	r1, [r7, #8]
	b	.L3
.L4:
.L2:
	add	sp, sp, #12
	pop	{r7, pc}
.Lfe1:
	.size	 test,.Lfe1-test
