@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	test
	.type	 test,function
	.thumb_func
test:
	push	{r4, lr}
	add	r3, r0, #0
	mov	r2, #0
	cmp	r2, r1
	bge	.L4	@cond_branch
	mov	r4, #0
.L6:
	add	r0, r3, r2
	strb	r4, [r0]
	add	r2, r2, #1
	cmp	r2, r1
	blt	.L6	@cond_branch
.L4:
	pop	{r4, pc}
.Lfe1:
	.size	 test,.Lfe1-test
